jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: yarn
      - run: cd components && yarn eslint
      - run: cd components && yarn stylelint
      - run: cd components && yarn test
