jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: yarn
      - run: yarn eslint
      - run: yarn stylelint
      - run: yarn test
      - run: yarn cov
