version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout

      - run:
        name: Install Dependencies
        command: yarn

      - run:
        name: Run eslint
        command: yarn eslint

      - run:
        name: Run stylelint
        command: yarn stylelint

      - run:
        name: Run unit tests
        command: yarn test

      - run:
        name: Run codecov
        command: yarn cov
